version: "3.5"
services:
  springapp:
    image: mallikarjunamothukuri/spring-boot:1
    depends_on:
    - mongo
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=demo
    - MONGO_DB_USERNAME=mallikarjuna
    - MONGO_DB_PASSWORD=password
    networks:
    - test1
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mallikarjuna
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - mongovol:/data/db
    networks:
    - test1
volumes:
  mongovol:

networks:
  test1:
        # external: true
